[phases.setup]
nixPkgs = ["python39", "nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build phase'"]

[start]
cmd = "cd backend && python main.py"

[variables]
PYTHON_VERSION = "3.9"
PORT = "8000"