[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["python -m pip install -r requirements-minimal.txt"]

[phases.build]
cmds = ["mkdir -p backend/data backend/models"]

[start]
cmd = "python start.py"

[variables]
PYTHON_VERSION = "3.9"
PORT = "8000"